### ISSUE TITLE
Request to Merge PR #3705 - Logo Update For BDE

### ISSUE THREAD

**Issue by bigchickendefi** [solana-labs/token-list#5571]
- **I'm submitting a request to manually merge a coin logo update. PR [#3705](https://github.com/solana-labs/token-list/pull/3705/files)

- Updated Logo under the assets/mainnet/H5gczCNbrtso6BqGKihF97RaWaxpUEZnFuFUKK4YX3s2/logo.png and updated src/tokens/solana.tokenlist.json // Unable to automerge, i have been stuck here for over 2 weeks now.

**Comment by keone** [comment]
logoURI now appears twice: https://github.com/solana-labs/token-list/pull/3705/files
please have whoever originally committed the addition of BDE reply in this thread that this is ok

**Comment by keone** [comment]
@bigchickendefi please submit a correct PR that deletes the old logoURI line instead of just adding a second line

**Comment by bigchickendefi** [comment]
fixed #3705 to include only one logo link

Thanks again!

**Comment by keone** [comment]
Sorry, it's still failing to merge easily because it's against such an old state of the repo.  Can you please rebase it to the current state of main and squash into a single commit, that will make it a lot easier to merge in

**Comment by bigchickendefi** [comment]
updated the logo, and the mainnet asset in a new PR, #6212 

Fetching upstream has been having some issues, so my apologies.
Hopefully this one works.

**Comment by keone** [comment]
Looks better now, this should automerge (if it doesnt i will manually merge)
